services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hack-backend
    ports:
      - "8080:8080"
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    networks:
      - hack-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hack-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - hack-network

networks:
  hack-network:
    driver: bridge
